apiVersion: v1
kind: Service
metadata:
  name: iris-api-nodeport
spec:
  selector:
    app: iris-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080   # you can change if this port is taken
