name: CI (test) + Build & Push to GHCR + Local Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write   # needed to push to GHCR

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pip)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Train model (bakes model.joblib)
        run: python train.py

      - name: Run unit tests
        run: pytest -q

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push Docker image (sha + latest)
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

  deploy-local:
    # Runs on YOUR Windows self-hosted runner
    runs-on: self-hosted
    needs: build-test-publish
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Tool versions
        shell: powershell
        run: |
          where.exe kubectl
          where.exe docker
          kubectl version --client
          docker --version

      - name: Use Docker Desktop context
        shell: powershell
        run: |
          kubectl config use-context docker-desktop
          kubectl get nodes -o wide

      - name: Show k8s manifests in repo
        shell: powershell
        run: |
          Get-ChildItem k8s
          Write-Host "---- deployment.yaml (first 20 lines) ----"
          Get-Content k8s/deployment.yaml | Select-Object -First 20
          if (Test-Path k8s/service.nodeport.yaml) {
            Write-Host "---- service.nodeport.yaml (first 20 lines) ----"
            Get-Content k8s/service.nodeport.yaml | Select-Object -First 20
          }

      - name: Apply manifests (everything under k8s/)
        shell: powershell
        run: |
          kubectl apply -f k8s --recursive --v=4

      - name: Roll out exact image built for this commit
        shell: powershell
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          Write-Host "Rolling out $env:IMAGE"
          kubectl set image deployment/iris-api api=$env:IMAGE --record
          kubectl rollout status deployment/iris-api --timeout=300s
          kubectl get deployment iris-api -o jsonpath="{.spec.template.spec.containers[0].image}"; echo
          kubectl get pods -l app=iris-api -o wide
